// <auto-generated />
using System;
using CustomerOnboard.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomerOnboard.Infrastructure.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    [Migration("20241123084736_AddIsBiometricEnabled")]
    partial class AddIsBiometricEnabled
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CustomerOnboarding.Core.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailOTP")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EmailOTPExpiry")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasPrivacyPolicyAgreed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ICNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnableBiometric")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MobileOTP")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MobileOTPExpiry")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pin")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
